---
title: "Multiple response"
author: "Thomas Lumley"
date: "7/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Representation: logical vector with TRUE/FALSE/NA and labels

```{r}
ethnicity <- matrix( c(T,F,F,F,F,
                       T,T,F,F,F,
                       F,T,F,F,F,
                       F,T,T,F,F,
                       NA,NA,F,F,F,
                       T,NA,F,T,F), byrow=TRUE,ncol=5)
colnames(ethnicity)<-c("European","M훮ori","Pacific","Asian","MELAA")
attr(ethnicity,"class")<-"mr"
```


Coercion from `mr` objects 

```{r}

levels.mr<-function(x,...) colnames(x)
"levels<-.mr"<-function(x, value) {
  colnames(x)<-value
  x
}

as.logical.mr<-function(x,...){
  unclass(x)
}

mr_na<-function(x, na=TRUE){
  y<-as.logical(x)
  y[is.na(y)]<-na
  levels(y)<-levels(x)
  class(y)<-"mr"
  y
}
    
as.character.mr<-function(x,sep="+",na.rm=TRUE){
  levels<-levels(x)
  if (na.rm) {
    x<-unclass(mr_na(x, na=FALSE))
    x<-lapply(seq_len(NROW(x)), function(i) levels[x[i,]])
  } else  {
    z<-unclass(mr_na(x,na=TRUE))
    tmp<-lapply(seq_len(NROW(x)),function(i) ifelse(is.na(x[i,])[z[i,]], paste0("?",levels[z[i,]]), levels[z[i,]]))
    x<-tmp
  }
  sapply(x,paste,collapse=sep)
}

as.character(ethnicity,na.rm=TRUE)
as.character(ethnicity,na.rm=FALSE)
```

Basic manipulations

```{r}
"[.mr"<-function(x,i,j){
  levels<-levels(x)
  x<-as.logical(x)[i,j,drop=FALSE]
  new_levels<-levels[j]
  class(x)<-"mr"
  levels(x)<-new_levels
  x
}
length.mr<-function(x) NROW(x)

length(ethnicity)
ethnicity[1,]
ethnicity[1:2,]
ethnicity[,1:2]
```


Print method
```{r}
print.mr <-function(x,...,na.rm=FALSE,sep="+"){
  x<-as.character(x,na.rm=na.rm,sep=sep)
  print(x)
}

ethnicity
ethnicity[1,]
ethnicity[1:2,]
ethnicity[,1:2]
```

Relational operator
```{r}
"%has%"<- function(x,y) {
  if (is.factor(y)) y<-as.character(y)
  if (!is.character(y)) stop('needs to be character or factor')
  if(length(y)==1) y<-rep(y,length(x))
  ifelse(y %in% levels(x), unclass(x)[,match(y,levels(x))] ,FALSE)
}

ethnicity %has% "M훮ori"

mr_count<-function(x,na.rm=TRUE) rowSums(x,na.rm=na.rm)

"%hasonly%"<- function(x,y) {
  (x %has% y) & (mr_count(x)==1)
}

ethnicity %hasonly% "M훮ori"
```

Adding and subtracting
```{r}
mr_union<-function(x,y){
  x<-as.mr(x)
  y<-as.mr(y)
  if (length(x)!=length(y)) 
    stop("different numbers of observations in x and y")
  levs<-unique(c(levels(x),levels(y)))
  m<-matrix(FALSE,nrow=nrow(x),ncol=length(levs))
  colnames(m)<-levs
  m[,levels(x)]<-x
  m[,levels(y)]<-m[,levels(y)] | y
  class(m)<-"mr"
  m
}
mr_diff<-function(x,y){
  x<-as.mr(x)
  y<-as.mr(y)
  if (length(x)!=length(y)) 
    stop("different numbers of observations in x and y")
  if(!all(levels(y) %in% levels(x)))
    stop("levels of y must be a subset of levels of x")
  levs<-levels(x)
  ilevs<-intersect(levs,levels(y))
  m<-matrix(FALSE,nrow=nrow(x),ncol=length(levs))
  colnames(m)<-levs
  m[,levs]<-x[,levs]
  m[,ilevs]<-m[,ilevs] & !y[,ilevs]
  class(m)<-"mr"
  m
}
mr_intersect<-function(x,y){
  x<-as.mr(x)
  y<-as.mr(y)
  if (length(x)!=length(y)) 
    stop("different numbers of observations in x and y")
  levs<-intersect(levels(x),levels(y))
  if (!length(levs)){
    warning("x and y have no levels in common")
  }
  m<-matrix(FALSE,nrow=nrow(x),ncol=length(levs))
  colnames(m)<-levs
  m[,levs]<-x[,levs] & y[,levs]
  class(m)<-"mr"
  m
}
```



```{r}
mr_reorder<-function(x, v, fun=median){
  values<-apply(x, 2, function(xi) fun(v[xi]))
  x<-x[,order(values)]
  x
}
mr_inseq<-function(x){
  x<-x[,order(colnames(x))]
  x
}
mr_inorder<-function(x){
  pos<-apply(as.logical(x),2, function(xi) min(which(xi)))
  x<-x[,order(pos)]
  x
}
mr_infreq<-function(x, na.rm=TRUE){
  y<-mr_na(x, na=!na.rm)
  freqs<-colSums(x)  
  x<-x[,order(-freqs)]
  x
}
```


Prioritised collapsing
```{r}
prioritise<-function(x, priorities){
  y<-rep(NA_character_,length(x))
  for(l in rev(priorities)){
    y<-ifelse(x %has% l,l,y)
  }
  factor(y,levels=levels(x))
}

pr_eth<-prioritise(ethnicity, c("M훮ori","Pacific","Asian","MELAA","European"))
str(pr_eth)
```


Tidying to individual indicators (like `gather`)

```{r}
stack.mr<-function(x,...,na.rm=FALSE){
  levels<-levels(x)
  x<-unclass(x)
  x[is.na(x)]<-!na.rm
  r<-rowSums(x)
  values<-do.call(c,lapply(seq_len(NROW(x)),function(i) levels[x[i,]]))
  id<-rep(seq_len(NROW(x)),r)
  data.frame(values=factor(values,levels=levels),id)
}
stack(ethnicity)
```

```{r}
indicator<-function(x, ...){
  xx<-1L*unclass(x)
  colnames(xx)<-levels(x)
  xx
}
indicator(ethnicity)
```


```{r}

as.mr<-function(x,...) UseMethod("as.mr",x)
as.mr.mr<-function(x,...) x
as.mr.default<-function(x,levels=unique(x)){
  rval<-outer(x,levels,"==")
  colnames(rval)<-levels
  class(rval)<-"mr"
  rval
}

as.mr.factor<-function(x,...){
  rval<-outer(x,levels(x),"==")
  colnames(rval)<-levels(x)
  class(rval)<-"mr"
  rval
}

mtable<-function(x,y,na.rm=TRUE){
  x<-as.mr(x)
  if (missing(y)){
    rval<-matrix(colSums(x,na.rm=na.rm),nrow=1)
    dimnames(rval)<-list("",levels(x))
    rval
  } else {
    y<-as.mr(y)
    xx<-unclass(x)
    if(na.rm) xx[is.na(xx)]<-FALSE
    yy<-unclass(y)
    if(na.rm) yy[is.na(yy)]<-FALSE
    rval<-crossprod(xx,yy)
    dimnames(rval)<-list(levels(x),levels(y))
    rval
  }
}

mtable(ethnicity)
mtable(1:6,ethnicity)
mtable(pr_eth,ethnicity)
```


